### PR TITLE
AMM-514 : 1097- Moving back to previous page take more time 

### PR DESCRIPTION
**Pull request by ravishanigarapu**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.  

# Type of change  

- [x] Bug fix  
- [ ] New feature  
- [x] Enhancement  
- [ ] Refactoring  
- [ ] Documentation  
- [ ] Other ( please specify )  

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by devikasuresh20** [comment]
@ravishanigarapu  Pls add Jira ticket Id also in PR Title.

**Comment by ravishanigarapu** [comment]
> @ravishanigarapu Pls add Jira ticket Id also in PR Title.

Done

**Review by devikasuresh20 — APPROVED** [review]
looks fine.

**Comment by drtechie** [comment]
Hi @ravishanigarapu 

Can you explain how this one query fixes the delay in API response?
Also, some lines have been removed. What about them?

**Comment by ravishanigarapu** [comment]
Hi @drtechie , Previously they were running multiple DB queries over a loop which is resulting in delay of API response(for example, if a phone number has 10 records then loop is running for each phone number for all 9 DB queries. which total results of 90 DB calls) . Now i have removed multiple queries and added a single query which does the work of those multiple queries. Hence only A single DB query is called for each phone number which reduces the api call time.

**Review by drtechie — APPROVED** [review]

**Comment by drtechie** [comment]
Thanks @ravishanigarapu

**Pull request merged**
